#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Twist
from geometry_msgs.msg import Pose

def iniciar():
    rospy.init_node('env', anonymous=True)
    velocidad_pub = rospy.Publisher('velocidades', Twist, queue_size=10)
    posicion_pub = rospy.Publisher('posicion', Pose, queue_size=10)
    vel_msg = Twist()
    pos_msg = Pose()

    while not rospy.is_shutdown():
	vel_msg.linear.x = 1
	vel_msg.linear.y = 1
	vel_msg.angular.z = 0

	pos_msg.position.x = 1.1
	pos_msg.position.y = 1.5

	velocidad_pub.publish(vel_msg)
	posicion_pub.publish(pos_msg)

if __name__ == '__main__':
    try:
	iniciar()
    except rospy.ROSInterruptException:
	pass

