#!/usr/bin/env python
import rospy
from geometry_msgs.msg import Twist
global Vlx
Vlx = 0

def callback(data):
    global Vlx
    Vlx = data.linear.x

def iniciar():
    rospy.init_node('rec', anonymous=True)
    rospy.Subscriber('velocidades', Twist, callback)

    while not rospy.is_shutdown():
	print Vlx

if __name__ == '__main__':
    try:
	iniciar()
    except rospy.ROSInterruptException:
	pass

