// Generated by gencpp from file auto_guidance/Waypoint.msg
// DO NOT EDIT!


#ifndef AUTO_GUIDANCE_MESSAGE_WAYPOINT_H
#define AUTO_GUIDANCE_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace auto_guidance
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : is_docking(false)
    , emergency_stop(false)
    , sound_alarm(false)
    , next_waypoint()  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : is_docking(false)
    , emergency_stop(false)
    , sound_alarm(false)
    , next_waypoint(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_docking_type;
  _is_docking_type is_docking;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;

   typedef uint8_t _sound_alarm_type;
  _sound_alarm_type sound_alarm;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _next_waypoint_type;
  _next_waypoint_type next_waypoint;





  typedef boost::shared_ptr< ::auto_guidance::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_guidance::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::auto_guidance::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::auto_guidance::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::auto_guidance::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_guidance::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_guidance::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_guidance

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'auto_guidance': ['/home/ubuntu/ros_ws/src/auto_guidance/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_guidance::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_guidance::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_guidance::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_guidance::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_guidance::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_guidance::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_guidance::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33b500f863be8e9520c2ee5c02322066";
  }

  static const char* value(const ::auto_guidance::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33b500f863be8e95ULL;
  static const uint64_t static_value2 = 0x20c2ee5c02322066ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_guidance::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_guidance/Waypoint";
  }

  static const char* value(const ::auto_guidance::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_guidance::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_docking\n\
bool emergency_stop\n\
bool sound_alarm\n\
geometry_msgs/Pose next_waypoint\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::auto_guidance::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_guidance::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_docking);
      stream.next(m.emergency_stop);
      stream.next(m.sound_alarm);
      stream.next(m.next_waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_guidance::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_guidance::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "is_docking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_docking);
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
    s << indent << "sound_alarm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sound_alarm);
    s << indent << "next_waypoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.next_waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_GUIDANCE_MESSAGE_WAYPOINT_H
