# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auto_guidance/ShuttleStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ShuttleStatus(genpy.Message):
  _md5sum = "887f812576610bde86685cae1b654708"
  _type = "auto_guidance/ShuttleStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Shuttle Status 

int8 error_code
int16 encoder_speed
bool initialization_status
int8 charging_level
"""
  __slots__ = ['error_code','encoder_speed','initialization_status','charging_level']
  _slot_types = ['int8','int16','bool','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error_code,encoder_speed,initialization_status,charging_level

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ShuttleStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.error_code is None:
        self.error_code = 0
      if self.encoder_speed is None:
        self.encoder_speed = 0
      if self.initialization_status is None:
        self.initialization_status = False
      if self.charging_level is None:
        self.charging_level = 0
    else:
      self.error_code = 0
      self.encoder_speed = 0
      self.initialization_status = False
      self.charging_level = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_bhBb().pack(_x.error_code, _x.encoder_speed, _x.initialization_status, _x.charging_level))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.error_code, _x.encoder_speed, _x.initialization_status, _x.charging_level,) = _get_struct_bhBb().unpack(str[start:end])
      self.initialization_status = bool(self.initialization_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_bhBb().pack(_x.error_code, _x.encoder_speed, _x.initialization_status, _x.charging_level))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.error_code, _x.encoder_speed, _x.initialization_status, _x.charging_level,) = _get_struct_bhBb().unpack(str[start:end])
      self.initialization_status = bool(self.initialization_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bhBb = None
def _get_struct_bhBb():
    global _struct_bhBb
    if _struct_bhBb is None:
        _struct_bhBb = struct.Struct("<bhBb")
    return _struct_bhBb
