# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auto_guidance/Waypoint.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Waypoint(genpy.Message):
  _md5sum = "33b500f863be8e9520c2ee5c02322066"
  _type = "auto_guidance/Waypoint"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool is_docking
bool emergency_stop
bool sound_alarm
geometry_msgs/Pose next_waypoint

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['is_docking','emergency_stop','sound_alarm','next_waypoint']
  _slot_types = ['bool','bool','bool','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       is_docking,emergency_stop,sound_alarm,next_waypoint

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Waypoint, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.is_docking is None:
        self.is_docking = False
      if self.emergency_stop is None:
        self.emergency_stop = False
      if self.sound_alarm is None:
        self.sound_alarm = False
      if self.next_waypoint is None:
        self.next_waypoint = geometry_msgs.msg.Pose()
    else:
      self.is_docking = False
      self.emergency_stop = False
      self.sound_alarm = False
      self.next_waypoint = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3B7d().pack(_x.is_docking, _x.emergency_stop, _x.sound_alarm, _x.next_waypoint.position.x, _x.next_waypoint.position.y, _x.next_waypoint.position.z, _x.next_waypoint.orientation.x, _x.next_waypoint.orientation.y, _x.next_waypoint.orientation.z, _x.next_waypoint.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.next_waypoint is None:
        self.next_waypoint = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 59
      (_x.is_docking, _x.emergency_stop, _x.sound_alarm, _x.next_waypoint.position.x, _x.next_waypoint.position.y, _x.next_waypoint.position.z, _x.next_waypoint.orientation.x, _x.next_waypoint.orientation.y, _x.next_waypoint.orientation.z, _x.next_waypoint.orientation.w,) = _get_struct_3B7d().unpack(str[start:end])
      self.is_docking = bool(self.is_docking)
      self.emergency_stop = bool(self.emergency_stop)
      self.sound_alarm = bool(self.sound_alarm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3B7d().pack(_x.is_docking, _x.emergency_stop, _x.sound_alarm, _x.next_waypoint.position.x, _x.next_waypoint.position.y, _x.next_waypoint.position.z, _x.next_waypoint.orientation.x, _x.next_waypoint.orientation.y, _x.next_waypoint.orientation.z, _x.next_waypoint.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.next_waypoint is None:
        self.next_waypoint = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 59
      (_x.is_docking, _x.emergency_stop, _x.sound_alarm, _x.next_waypoint.position.x, _x.next_waypoint.position.y, _x.next_waypoint.position.z, _x.next_waypoint.orientation.x, _x.next_waypoint.orientation.y, _x.next_waypoint.orientation.z, _x.next_waypoint.orientation.w,) = _get_struct_3B7d().unpack(str[start:end])
      self.is_docking = bool(self.is_docking)
      self.emergency_stop = bool(self.emergency_stop)
      self.sound_alarm = bool(self.sound_alarm)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B7d = None
def _get_struct_3B7d():
    global _struct_3B7d
    if _struct_3B7d is None:
        _struct_3B7d = struct.Struct("<3B7d")
    return _struct_3B7d
